name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          cache: true

      - uses: golangci/golangci-lint-action@v6
        with:
          install-mode: "install-only"

      - run: make build
      - run: make test
      - run: make lint
